steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install']
- name: "gcr.io/cloud-builders/gcloud"  
  args: ["app", "create"]
  env:
  - '--region=us-central1'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
- name: "gcr.io/cloud-builders/gcloud"  
  args: ["app", "deploy"]
  env:
  - '--region=us-central1'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  timeout: "1600s"
